# ds5-setup.ps1
# ===========================================================================
# DS5Dongle automation installer.
# Run this once (via ds5-setup.bat). It detects its own folder and generates
# all the automation scripts with the correct paths baked in, so you never edit
# a path by hand. Re-running is safe (it overwrites the generated files).
#
# It generates, next to itself:
#   ds5-global-start.ps1   ds5-global-stop.ps1
#   ds5-start.bat          ds5-stop.bat
#   native-games.txt       (only if missing - never overwrites your list)
#
# It expects these to already be present in the same folder:
#   ds5audio.py
#   profiles\audio-mix.autoapply.html
#   profiles\native-off.autoapply.html
#
# PowerShell 5.1-safe. Pure ASCII.
# ===========================================================================

# Base = the folder this installer lives in.
$Base = $PSScriptRoot
if (-not $Base) { $Base = Split-Path -Parent $MyInvocation.MyCommand.Definition }

Write-Host ""
Write-Host "DS5Dongle automation setup"
Write-Host "=========================="
Write-Host "Install folder: $Base"
Write-Host ""

# --- Sanity checks: warn (don't fail) if expected assets are missing. ---
$audioPy    = Join-Path $Base "ds5audio.py"
$profMix    = Join-Path $Base "profiles\audio-mix.autoapply.html"
$profNative = Join-Path $Base "profiles\native-off.autoapply.html"

function Check($path, $label) {
    if (Test-Path -LiteralPath $path) { Write-Host "  [OK]   $label" }
    else { Write-Host "  [WARN] missing: $label  ($path)" }
}
Check $audioPy    "ds5audio.py"
Check $profMix    "profiles\audio-mix.autoapply.html"
Check $profNative "profiles\native-off.autoapply.html"
Write-Host ""

# Helper to write a file from a here-string, substituting {{BASE}}.
function Write-Generated($name, $content) {
    $full = Join-Path $Base $name
    $out = $content.Replace("{{BASE}}", $Base)
    Set-Content -LiteralPath $full -Value $out -Encoding ASCII
    Write-Host "  wrote $name"
}

# ===========================================================================
# 1. ds5-global-start.ps1
# ===========================================================================
$startPs1 = @'
# ds5-global-start.ps1  (generated by ds5-setup - do not hand-edit)
# -ShowWindow : TEST MODE - launches ds5audio in a visible console that stays
#               open even if Python crashes, and mirrors log lines to screen.
param([string]$GameName = "", [switch]$ShowWindow, [switch]$GrantSetup)

# Self-detect our own folder so paths never go stale if the folder is moved.
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition }
$DS5Dir        = $scriptDir
$NativeList    = Join-Path $DS5Dir "native-games.txt"
# Default profiles: an .html filename in profiles\, OR "slot N" (N = 1-24) to
# activate a profile saved ON THE DONGLE - one atomic command via the self-
# closing slot page: faster than a field-by-field html apply, and no window
# stays open. Example: $AudioProfile = "slot 1"
$NativeProfile = "native-off.autoapply.html"
$AudioProfile  = "audio-mix.autoapply.html"
$AudioScript   = Join-Path $DS5Dir "ds5audio.py"
$AudioArgs     = @()   # e.g. @("--capture-name","SONY TV") to pin a capture device
$PythonExe     = ""    # OPTIONAL: full path to the python.exe that has PyAudioWPatch
                       # installed (the one that works when you run it manually).
                       # Leave "" to auto-detect from PATH.
$LogFile       = Join-Path $DS5Dir "ds5-automation.log"

function Log($m) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -LiteralPath $LogFile -Value "$ts  [start] $m" -Encoding UTF8
    if ($ShowWindow) { Write-Host "[start] $m" }
}

$gameName = $GameName
if (-not $gameName) { try { if ($game -and $game.Name) { $gameName = [string]$game.Name } } catch { } }
# Fallback: Playnite's "before starting" event often does NOT expand {Name}, and the
# .bat runs outside Playnite's runtime (no $game). Read the launching game from
# Playnite's own log as a last resort.
if (-not $gameName) {
    $plog = Join-Path $env:APPDATA "Playnite\playnite.log"
    if (Test-Path -LiteralPath $plog) {
        try {
            $lines = Get-Content -LiteralPath $plog -Tail 200 -Encoding UTF8 -ErrorAction SilentlyContinue
            for ($i = $lines.Count - 1; $i -ge 0; $i--) {
                $mm = [regex]::Match($lines[$i], "(?:Starting|Started)\s+(.+?)(?:\s+game\b|\s*$)")
                if ($mm.Success -and $mm.Groups[1].Value.Trim()) { $gameName = $mm.Groups[1].Value.Trim().Trim('"').Trim("'"); Log "name from playnite.log: '$gameName'"; break }
            }
            if (-not $gameName) { Log "playnite.log tail (format diagnosis):"; foreach ($ln in ($lines | Select-Object -Last 6)) { Log "  | $ln" } }
        } catch { Log "playnite.log read failed: $($_.Exception.Message)" }
    } else { Log "playnite.log not found at $plog" }
}
Log "game: '$gameName'"

$isNative = $false
if (Test-Path -LiteralPath $NativeList) {
function Normalize-Name([string]$s) {
    # Fold to lowercase ASCII. This survives BOTH accented characters and
    # mojibake: 'Ragnar\u00f6k' sent as UTF-8 but decoded as ANSI arrives as
    # 'Ragnar\u00c3\u00b6k'; dropping every non-ASCII char makes both sides equal
    # ('ragnark'), so the native match works no matter which layer mangled it.
    if (-not $s) { return "" }
    (($s.ToLowerInvariant()).ToCharArray() | Where-Object { [int]$_ -ge 32 -and [int]$_ -le 126 }) -join ""
}
    # -Encoding UTF8 so accented list entries read correctly in PowerShell 5.1
    # (which otherwise assumes ANSI for BOM-less files).
    $needles = Get-Content -LiteralPath $NativeList -Encoding UTF8 -ErrorAction SilentlyContinue | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and -not $_.StartsWith("#") }
    $gnorm = Normalize-Name $gameName
    foreach ($n in $needles) {
        $nn = Normalize-Name $n
        $hit = if ($nn) { $gnorm.Contains($nn) }
               else { $gameName -and $gameName.ToLower().Contains($n.ToLower()) } # non-Latin entry: raw compare
        if ($hit) { $isNative = $true; Log "matched native entry: '$n'"; break }
    }
} else { Log "WARN native list not found: $NativeList" }

# --- Per-game profile override (optional) ---
# profile-overrides.txt lines:   name fragment = profile-file.html [, audio|noaudio]
# First matching line wins; the profile file must be in profiles\. The optional
# audio/noaudio flag forces the capture decision; when omitted, the native list
# decides as usual. Matching uses the same mojibake-proof fold as native-games.
$overrideProfile = $null; $overrideAudio = $null; $overrideAudioArgs = @()
$bestLen = 0; $bestFrag = $null   # longest override fragment matched so far
$OverrideFile = Join-Path $DS5Dir "profile-overrides.txt"
if (Test-Path -LiteralPath $OverrideFile) {
    $gof = Normalize-Name $gameName
    foreach ($line in (Get-Content -LiteralPath $OverrideFile -Encoding UTF8 -ErrorAction SilentlyContinue)) {
        $t = "$line".Trim()
        if ($t -eq "" -or $t.StartsWith("#")) { continue }
        $kv = $t -split "=", 2
        if ($kv.Count -lt 2) { continue }
        $frag = $kv[0].Trim()
        # spec [, audio|noaudio] [, <ds5audio arguments>]
        # Anything after the spec that is not the audio flag is passed straight
        # to ds5audio.py, so a profile that needs a particular channel mapping
        # (e.g. "--map front" for a game whose own haptics must stay on ch3/4)
        # can carry it. $AudioArgs stays as the global default for every game.
        $file = $kv[1].Trim(); $flag = $null; $xargs = @()
        $cm = $file -split ","
        if ($cm.Count -gt 1) {
            $file = $cm[0].Trim()
            foreach ($tok in $cm[1..($cm.Count - 1)]) {
                $tv = "$tok".Trim()
                if ($tv -eq "") { continue }
                if ($tv.ToLower() -eq "audio" -or $tv.ToLower() -eq "noaudio") { $flag = $tv.ToLower() }
                else { $xargs += ($tv -split '\s+' | Where-Object { $_ -ne "" }) }
            }
        }
        if (-not $frag -or -not $file) { continue }
        $fn = Normalize-Name $frag
        $hit = if ($fn) { $gof.Contains($fn) } else { $gameName -and $gameName.ToLower().Contains($frag.ToLower()) }
        if ($hit) {
            # LONGEST fragment wins, not the first one in the file.
            #
            # Matching is a SUBSTRING test, so a short entry swallows every
            # sequel that contains it: 'God of War' matched 'God of War
            # Ragnarok' and loaded its slot, silently overriding a correct
            # native classification. Taking the first hit made the answer depend
            # on line order in profile-overrides.txt, which nothing tells you
            # about and which is easy to disturb by adding a line.
            $len = if ($fn) { $fn.Length } else { $frag.Length }
            if ($len -gt $bestLen) {
                if ($bestLen -gt 0) {
                    Log "  more specific than '$bestFrag' - using the longer match"
                }
                $bestLen  = $len
                $bestFrag = $frag
                $overrideProfile = $file
                $overrideAudio = if ($flag -eq "audio" -or $flag -eq "noaudio") { $flag } else { $overrideAudio }
                $overrideAudioArgs = if ($xargs.Count) { $xargs } else { $overrideAudioArgs }
                $fl = if ($flag) { " ($flag)" } else { "" }
                $xa = if ($xargs.Count) { " args: " + ($xargs -join " ") } else { "" }
                Log "matched override entry: '$frag' -> '$file'$fl$xa"
            } else {
                Log "  ignoring shorter override entry '$frag' ('$bestFrag' is more specific)"
            }
        }
    }
}

$global:DS5WasNative = $isNative

$BrowserExe      = "msedge"  # browser for profile pages, launched with --new-window
                             # so minimizing never touches your other tabs, and the
                             # page's self-close closes the whole window when done.
                             # Set "" to use the default handler (no minimize then).
$MinimizeBrowser = $true     # minimize the profile window right after it opens
$UseLocalServer  = $false    # keep $false: file:// is where existing grants live

function Resolve-Browser {
    if (-not $BrowserExe) { return $null }
    if (Test-Path -LiteralPath $BrowserExe) { return $BrowserExe }
    $c = Get-Command $BrowserExe -ErrorAction SilentlyContinue
    if ($c -and $c.Source) { return $c.Source }
    foreach ($g in @("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
                     "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")) {
        if ($g -and (Test-Path -LiteralPath $g)) { return $g }
    }
    return $BrowserExe  # last resort: ShellExecute App Paths lookup
}

function Ensure-DS5WinType {
    if ("DS5.Win" -as [type]) { return }
    Add-Type -ErrorAction Stop -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
namespace DS5 {
  public static class Win {
    delegate bool EnumProc(IntPtr h, IntPtr l);
    [DllImport("user32.dll")] static extern bool EnumWindows(EnumProc cb, IntPtr l);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] static extern int GetWindowText(IntPtr h, StringBuilder s, int n);
    [DllImport("user32.dll")] static extern bool IsWindowVisible(IntPtr h);
    [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr h, int cmd);
    [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr h, uint msg, IntPtr w, IntPtr l);
    public static List<IntPtr> FindByTitle(string frag) {
      var found = new List<IntPtr>();
      EnumWindows((h, l) => {
        if (!IsWindowVisible(h)) return true;
        var sb = new StringBuilder(512);
        GetWindowText(h, sb, 512);
        if (sb.ToString().IndexOf(frag, StringComparison.OrdinalIgnoreCase) >= 0) found.Add(h);
        return true;
      }, IntPtr.Zero);
      return found;
    }
  }
}
"@
}

function Get-DS5Windows([string]$titleFrag) {
    try { Ensure-DS5WinType } catch { Log "WARN user32 helper unavailable: $($_.Exception.Message)"; return @() }
    @([DS5.Win]::FindByTitle($titleFrag))
}

function Close-StaleProfileWindows {
    # Sweep leftover automation pages BEFORE opening a new one. Targets ONLY
    # titles the automation owns - stuck pages ("CONNECT NEEDED ..."), slot
    # activator pages ("DS5 Bridge Config - Slot"), and finished-but-unclosable
    # ones ("DS5 slot done") - so a portal tab in the user's own browser is
    # never touched. Prevents overlapping slot pages (exit-restore page still
    # alive when the next launch's page opens) from clobbering each other's
    # replies in the dongle's single reply buffer: that ping-pong left pages
    # piled up, and the LAST re-sent activation won the config - which could
    # re-activate the previous profile over the new one.
    $n = 0
    foreach ($frag in @("CONNECT NEEDED", "DS5 Bridge Config - Slot", "DS5 slot done")) {
        foreach ($h in (Get-DS5Windows $frag)) {
            [DS5.Win]::PostMessage($h, 0x0010, [IntPtr]::Zero, [IntPtr]::Zero) | Out-Null # WM_CLOSE
            $n++
        }
    }
    if ($n) { Log "closed $n stale profile window(s)"; Start-Sleep -Milliseconds 300 }
}

function Minimize-ProfileWindow([int]$timeoutMs = 6000) {
    # All profile pages carry the title "DS5 Bridge Config"; wait for such a
    # window, then minimize. Enumerates ALL top-level windows - Get-Process
    # exposes only ONE MainWindow per Edge process, which missed windows when
    # several existed. Pages keep full speed minimized (worker-based timers).
    $deadline = (Get-Date).AddMilliseconds($timeoutMs)
    while ((Get-Date) -lt $deadline) {
        $ws = Get-DS5Windows "DS5 Bridge Config"
        if ($ws.Count) {
            foreach ($h in $ws) { [DS5.Win]::ShowWindowAsync($h, 6) | Out-Null } # 6 = SW_MINIMIZE
            Log "minimized $($ws.Count) profile window(s)"
            return
        }
        Start-Sleep -Milliseconds 200
    }
    Log "note: profile window not seen to minimize (may have already self-closed)"
}

function Apply-Profile($htmlPath, $query = "") {
    if (-not (Test-Path -LiteralPath $htmlPath)) { Log "WARN profile not found: $htmlPath"; return }
    try {
        Close-StaleProfileWindows
        # Open the html FILE directly (file:// origin). That is the origin your
        # browser's existing WebHID grant is stored against, and the launch
        # method that has always worked. $UseLocalServer = $true switches to
        # http://127.0.0.1:$ProfilePort serving instead (only useful if your
        # browser refuses to persist file:// grants; better: install the
        # policy via ds5-policy.bat, which covers both origins).
        $target = $htmlPath
        if ($UseLocalServer -and (Ensure-ProfileServer)) {
            $target = "http://127.0.0.1:$ProfilePort/" + [System.IO.Path]::GetFileName($htmlPath) + $query
        } elseif ($query) {
            # query strings only survive on URIs, not bare paths
            $target = ([System.Uri]$htmlPath).AbsoluteUri + $query
        }
        $b = Resolve-Browser
        if ($b) {
            Start-Process -FilePath $b -ArgumentList "--new-window", "`"$target`"" -ErrorAction Stop | Out-Null
        } else {
            $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = $target; $psi.UseShellExecute = $true
            [System.Diagnostics.Process]::Start($psi) | Out-Null
        }
        Log "applied profile: $target"
        if ($b -and $MinimizeBrowser) { Minimize-ProfileWindow }
    } catch { Log "FAIL applying $htmlPath : $($_.Exception.Message)" }
}

# Turn a profile SPEC - "slot N" / "slot:N" (on-dongle slot, fw 1.1.2+) or a
# profile .html filename - into the page + query to open. $null if unusable.
function Resolve-DS5Profile([string]$spec) {
    if (-not $spec) { return $null }
    if ($spec -match '^(?i)slot[\s:]*([1-9]|[12][0-9]|3[0-2])$') {
        $p = Join-Path (Join-Path $DS5Dir "profiles") "slot-activate.html"
        if (Test-Path -LiteralPath $p) { return @{ Path = $p; Query = "?slot=$($Matches[1])" } }
        Log "WARN slot-activate.html missing - re-run ds5-setup"
        return $null
    }
    if ($spec -match '^(?i)slot[\s:]*([0-9]+)$') {
        Log "WARN slot number out of range: '$spec' - valid slots are 1-32 (fw 1.22.0+; 1-24 on 1.17.0-1.21.x; 1-16 before that)"
        return $null
    }
    $p = Join-Path (Join-Path $DS5Dir "profiles") $spec
    if (Test-Path -LiteralPath $p) { return @{ Path = $p; Query = "" } }
    Log "WARN profile not found: $p"
    return $null
}

# Build interpreter candidates in preference order. Do NOT exclude the
# Microsoft Store WindowsApps paths outright: when Python is installed FROM
# the Store, the real interpreter lives behind those exact paths. Non-Store
# paths are merely preferred; callers weed out fake alias stubs by checking
# whether the launched process actually does its job.
function Get-PythonCandidates {
    $pref  = @()
    $store = @()
    foreach ($name in @("pythonw", "python")) {
        foreach ($c in @(Get-Command $name -All -ErrorAction SilentlyContinue)) {
            if (-not $c.Source) { continue }
            if ($c.Source -like "*\Microsoft\WindowsApps\*") { $store += $c.Source }
            else { $pref += $c.Source }
        }
    }
    $out = @($pref) + @($store)
    # Last resort: the py launcher (installed by python.org installers
    # even when python itself is not on PATH).
    $pyl = Get-Command py -ErrorAction SilentlyContinue
    if ($pyl -and $pyl.Source) { $out += $pyl.Source }
    @($out | Select-Object -Unique)
}

$ProfilePort  = 8377
$ServerScript = Join-Path $DS5Dir "ds5-profile-server.py"

function Test-ProfileServer {
    try {
        $r = Invoke-WebRequest -Uri "http://127.0.0.1:$ProfilePort/__ds5" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        return ($r.Content -like "*ds5-profile-server*")
    } catch { return $false }
}

function Ensure-ProfileServer {
    if (Test-ProfileServer) { return $true }
    if (-not (Test-Path -LiteralPath $ServerScript)) { Log "WARN server script missing: $ServerScript"; return $false }
    foreach ($exe in @(Get-PythonCandidates)) {
        try {
            $argList = @()
            if ((Split-Path -Leaf $exe) -ieq "py.exe") { $argList += "-3" }
            $argList += "`"$ServerScript`""
            Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -ErrorAction Stop | Out-Null
        } catch { continue }
        for ($i = 0; $i -lt 10; $i++) {
            Start-Sleep -Milliseconds 300
            if (Test-ProfileServer) { Log "profile server started via $exe"; return $true }
        }
    }
    Log "WARN could not start profile server (port $ProfilePort busy, or no working python)"
    return $false
}

if ($GrantSetup) {
    # Manual per-session grant fallback (run: ds5-global-start.ps1 -GrantSetup):
    # opens a profile page UNminimized so you can click "Connect & Apply".
    # Prefer ds5-policy.bat, which pre-grants permanently with no clicks.
    $MinimizeBrowser = $false
    Apply-Profile $AudioProfile
    Log "grant-setup: page opened; click Connect & Apply once if prompted"
    return
}

# --- Decide which profile to apply and whether to run the capture ---
$profileToApply = $null; $startAudio = $false; $appliedSpec = $null
$ApplyQuery = ""
if ($overrideProfile) {
    # Overrides and defaults share one resolver: 'slot N' or an html filename.
    $res = Resolve-DS5Profile $overrideProfile
    if ($res) { $profileToApply = $res.Path; $ApplyQuery = $res.Query; $appliedSpec = $overrideProfile }
    else { Log "WARN override unusable: '$overrideProfile' - falling back to defaults" }
    if ($profileToApply) {
        if     ($overrideAudio -eq "audio")   { $startAudio = $true }
        elseif ($overrideAudio -eq "noaudio") { $startAudio = $false }
        else                                  { $startAudio = -not $isNative }
        Log "override -> '$overrideProfile'$ApplyQuery (audio: $startAudio)"
    }
}
if (-not $profileToApply) {
    $spec = if ($isNative) { $NativeProfile } else { $AudioProfile }
    $res = Resolve-DS5Profile $spec
    if ($res) { $profileToApply = $res.Path; $ApplyQuery = $res.Query; $appliedSpec = $spec }
    if ($isNative) { $startAudio = $false; Log "native -> OFF profile, no capture" }
    else           { $startAudio = $true }
}
# Remember whether the mix profile must be restored on exit. The stop script
# reads this file - it works across separate powershell invocations (the .bat
# path) and knows about overrides, unlike $global variables or a list recompute.
try {
    $stateVal = if ($appliedSpec -eq $AudioProfile) { "mix" } else { "restore-mix" }
    Set-Content -LiteralPath (Join-Path $DS5Dir "ds5-last-start.txt") -Value $stateVal -Encoding ASCII
} catch { }

Apply-Profile $profileToApply $ApplyQuery
# Global args first, then any the matched override added.
$EffAudioArgs = @($AudioArgs) + @($overrideAudioArgs)
if ($EffAudioArgs.Count) { Log ("ds5audio args: " + ($EffAudioArgs -join " ")) }

if ($startAudio) {
    if (-not (Test-Path -LiteralPath $AudioScript)) {
        Log "WARN audio script not found: $AudioScript"
    } else {
        # Find running ds5audio processes. Get-CimInstance works in both Windows
        # PowerShell 5.1 and PowerShell 7 (Playnite's newer hosted runtime);
        # Get-WmiObject exists only in 5.1, so it is the fallback, not the default.
        function Get-DS5AudioProcs {
            $f = "Name='python.exe' OR Name='pythonw.exe'"
            $list = $null
            try { $list = Get-CimInstance -ClassName Win32_Process -Filter $f -ErrorAction Stop }
            catch { try { $list = Get-WmiObject -Class Win32_Process -Filter $f -ErrorAction Stop } catch { $list = @() } }
            @($list | Where-Object { $_.CommandLine -like "*ds5audio.py*" })
        }
        foreach ($p in (Get-DS5AudioProcs)) {
            try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop; Log "stopped stray capture PID $($p.ProcessId)" } catch { }
        }
        # (Get-PythonCandidates is defined at top level - also used by the
        # profile server. Survival check below weeds out Store alias stubs.)
        $cands = @(Get-PythonCandidates)
        if ($PythonExe) {
            if (Test-Path -LiteralPath $PythonExe) { $cands = @($PythonExe); Log "using pinned PythonExe: $PythonExe" }
            else { Log "WARN pinned PythonExe not found ($PythonExe), falling back to auto-detect" }
        }
        if ($ShowWindow) {
            # Visible test mode needs a console interpreter, not pythonw.
            $vis = @($cands | Where-Object { (Split-Path -Leaf $_) -inotlike "pythonw*" })
            if ($vis.Count -gt 0) { $cands = $vis }
        }
        if ($cands.Count -eq 0) { Log "FAIL: no python/pythonw/py found on PATH" }
        else {
            Log ("python candidates: " + ($cands -join " | "))
            $started = $false
            foreach ($exe in $cands) {
                if ($started) { break }
                try {
                    $inner = ""
                    if ((Split-Path -Leaf $exe) -ieq "py.exe") { $inner = "-3 " }
                    $inner = "`"$exe`" $inner`"$AudioScript`""
                    foreach ($a in $EffAudioArgs) { $inner += " `"$a`"" }
                    if ($ShowWindow) {
                        # Run inside cmd /k so the window stays open even if
                        # Python exits/crashes instantly - you SEE the error.
                        $proc = Start-Process -FilePath "$env:ComSpec" -ArgumentList "/k `"$inner --verbose`"" -WorkingDirectory $DS5Dir -PassThru -ErrorAction Stop
                        Log "VISIBLE test launch via $exe (window stays open; close it to stop)"
                        $started = $true
                    } else {
                        $argList = @()
                        if ((Split-Path -Leaf $exe) -ieq "py.exe") { $argList += "-3" }
                        $argList += "`"$AudioScript`""
                        $argList += $EffAudioArgs
                        $proc = Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -PassThru -ErrorAction Stop
                        Start-Sleep -Milliseconds 1500
                        if ($proc.HasExited) {
                            Log "WARN $exe exited immediately (code $($proc.ExitCode)) - Store stub or startup error (see ds5audio.log); trying next"
                        } else {
                            Log "ds5audio started (PID $($proc.Id) via $exe)"
                            $started = $true
                        }
                    }
                } catch { Log "FAIL starting via $exe : $($_.Exception.Message)" }
            }
            if (-not $started) { Log "FAIL: ds5audio did not stay running - check ds5audio.log in $DS5Dir" }
        }
    }
    Log "non-native -> mix profile + capture"
}
'@
Write-Generated "ds5-global-start.ps1" $startPs1

# ===========================================================================
# 2. ds5-global-stop.ps1
# ===========================================================================
$stopPs1 = @'
# ds5-global-stop.ps1  (generated by ds5-setup - do not hand-edit)
param([string]$GameName = "")

# Self-detect our own folder so paths never go stale if the folder is moved.
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition }
$DS5Dir       = $scriptDir
$NativeList   = Join-Path $DS5Dir "native-games.txt"
$AudioProfile = "audio-mix.autoapply.html"   # or "slot N" - keep in sync with ds5-global-start.ps1
$LogFile      = Join-Path $DS5Dir "ds5-automation.log"

function Log($m) { $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"; Add-Content -LiteralPath $LogFile -Value "$ts  [stop]  $m" -Encoding UTF8 }

$wasNative = $false; $decided = $false
# Preferred source: the state file written by the start script. It survives
# separate powershell invocations (the .bat path) and knows about per-game
# profile overrides; "restore-mix" means the applied profile was NOT the mix
# profile, so the mix must be restored now.
try {
    $StateFile = Join-Path $DS5Dir "ds5-last-start.txt"
    if (Test-Path -LiteralPath $StateFile) {
        $sv = "$((Get-Content -LiteralPath $StateFile -ErrorAction Stop | Select-Object -First 1))".Trim()
        if     ($sv -eq "restore-mix") { $wasNative = $true;  $decided = $true }
        elseif ($sv -eq "mix")         { $wasNative = $false; $decided = $true }
    }
} catch { }
try { if (-not $decided -and $null -ne $global:DS5WasNative) { $wasNative = [bool]$global:DS5WasNative; $decided = $true } } catch { }
if (-not $decided) {
    $gn = $GameName
    if (-not $gn) { try { if ($game -and $game.Name) { $gn = [string]$game.Name } } catch { } }
    if ($gn -and (Test-Path -LiteralPath $NativeList)) {
        function Normalize-Name([string]$s) {
            if (-not $s) { return "" }
            (($s.ToLowerInvariant()).ToCharArray() | Where-Object { [int]$_ -ge 32 -and [int]$_ -le 126 }) -join ""
        }
        $needles = Get-Content -LiteralPath $NativeList -Encoding UTF8 -ErrorAction SilentlyContinue | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and -not $_.StartsWith("#") }
        $gnorm = Normalize-Name $gn
        foreach ($n in $needles) {
            $nn = Normalize-Name $n
            $hit = if ($nn) { $gnorm.Contains($nn) } else { $gn.ToLower().Contains($n.ToLower()) }
            if ($hit) { $wasNative = $true; break }
        }
    }
    Log "game: '$gn' (re-checked list)"
}
Log "wasNative = $wasNative"

# Always stop any ds5audio (safety net).
# Get-CimInstance works in both Windows PowerShell 5.1 and PowerShell 7
# (Playnite's newer hosted runtime); Get-WmiObject exists only in 5.1, so it
# is the fallback. Stop-Process works in both.
function Get-DS5AudioProcs {
    $f = "Name='python.exe' OR Name='pythonw.exe'"
    $list = $null
    try { $list = Get-CimInstance -ClassName Win32_Process -Filter $f -ErrorAction Stop }
    catch { try { $list = Get-WmiObject -Class Win32_Process -Filter $f -ErrorAction Stop } catch { $list = @() } }
    @($list | Where-Object { $_.CommandLine -like "*ds5audio.py*" })
}
$n = 0
foreach ($p in (Get-DS5AudioProcs)) {
    try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop; $n++; Log "stopped capture PID $($p.ProcessId)" }
    catch { Log "WARN could not stop PID $($p.ProcessId): $($_.Exception.Message)" }
}
Log "stopped $n audio capture process(es)"

function Ensure-DS5WinType {
    if ("DS5.Win" -as [type]) { return }
    Add-Type -ErrorAction Stop -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
namespace DS5 {
  public static class Win {
    delegate bool EnumProc(IntPtr h, IntPtr l);
    [DllImport("user32.dll")] static extern bool EnumWindows(EnumProc cb, IntPtr l);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] static extern int GetWindowText(IntPtr h, StringBuilder s, int n);
    [DllImport("user32.dll")] static extern bool IsWindowVisible(IntPtr h);
    [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr h, int cmd);
    [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr h, uint msg, IntPtr w, IntPtr l);
    public static List<IntPtr> FindByTitle(string frag) {
      var found = new List<IntPtr>();
      EnumWindows((h, l) => {
        if (!IsWindowVisible(h)) return true;
        var sb = new StringBuilder(512);
        GetWindowText(h, sb, 512);
        if (sb.ToString().IndexOf(frag, StringComparison.OrdinalIgnoreCase) >= 0) found.Add(h);
        return true;
      }, IntPtr.Zero);
      return found;
    }
  }
}
"@
}

function Get-DS5Windows([string]$titleFrag) {
    try { Ensure-DS5WinType } catch { Log "WARN user32 helper unavailable: $($_.Exception.Message)"; return @() }
    @([DS5.Win]::FindByTitle($titleFrag))
}

function Close-StaleProfileWindows {
    # Sweep leftover automation pages BEFORE opening a new one. Targets ONLY
    # titles the automation owns - stuck pages ("CONNECT NEEDED ..."), slot
    # activator pages ("DS5 Bridge Config - Slot"), and finished-but-unclosable
    # ones ("DS5 slot done") - so a portal tab in the user's own browser is
    # never touched. Prevents overlapping slot pages (exit-restore page still
    # alive when the next launch's page opens) from clobbering each other's
    # replies in the dongle's single reply buffer: that ping-pong left pages
    # piled up, and the LAST re-sent activation won the config - which could
    # re-activate the previous profile over the new one.
    $n = 0
    foreach ($frag in @("CONNECT NEEDED", "DS5 Bridge Config - Slot", "DS5 slot done")) {
        foreach ($h in (Get-DS5Windows $frag)) {
            [DS5.Win]::PostMessage($h, 0x0010, [IntPtr]::Zero, [IntPtr]::Zero) | Out-Null # WM_CLOSE
            $n++
        }
    }
    if ($n) { Log "closed $n stale profile window(s)"; Start-Sleep -Milliseconds 300 }
}

function Minimize-ProfileWindow([int]$timeoutMs = 6000) {
    # All profile pages carry the title "DS5 Bridge Config"; wait for such a
    # window, then minimize. Enumerates ALL top-level windows - Get-Process
    # exposes only ONE MainWindow per Edge process, which missed windows when
    # several existed. Pages keep full speed minimized (worker-based timers).
    $deadline = (Get-Date).AddMilliseconds($timeoutMs)
    while ((Get-Date) -lt $deadline) {
        $ws = Get-DS5Windows "DS5 Bridge Config"
        if ($ws.Count) {
            foreach ($h in $ws) { [DS5.Win]::ShowWindowAsync($h, 6) | Out-Null } # 6 = SW_MINIMIZE
            Log "minimized $($ws.Count) profile window(s)"
            return
        }
        Start-Sleep -Milliseconds 200
    }
    Log "note: profile window not seen to minimize (may have already self-closed)"
}

# Sweep stale automation pages on EVERY exit (native and non-native): a stuck
# or still-running page from the launch must not survive into the next
# launch's activation.
Close-StaleProfileWindows

if ($wasNative) {
    $restorePath = $null; $restoreQuery = ""
    if ($AudioProfile -match '^(?i)slot[\s:]*([1-9]|[12][0-9]|3[0-2])$') {
        $rp = Join-Path (Join-Path $DS5Dir "profiles") "slot-activate.html"
        if (Test-Path -LiteralPath $rp) { $restorePath = $rp; $restoreQuery = "?slot=$($Matches[1])" }
    } else {
        $rp = Join-Path (Join-Path $DS5Dir "profiles") $AudioProfile
        if (Test-Path -LiteralPath $rp) { $restorePath = $rp }
    }
    if ($restorePath) {
        $BrowserExe      = "msedge"  # keep in sync with ds5-global-start.ps1
        $MinimizeBrowser = $true
        $UseLocalServer  = $false    # keep in sync with ds5-global-start.ps1
        $ProfilePort     = 8377
        $ServerScript    = Join-Path $DS5Dir "ds5-profile-server.py"
        function Get-PythonCandidates {
            $pref = @(); $store = @()
            foreach ($name in @("pythonw", "python")) {
                foreach ($c in @(Get-Command $name -All -ErrorAction SilentlyContinue)) {
                    if (-not $c.Source) { continue }
                    if ($c.Source -like "*\Microsoft\WindowsApps\*") { $store += $c.Source } else { $pref += $c.Source }
                }
            }
            $out = @($pref) + @($store)
            $pyl = Get-Command py -ErrorAction SilentlyContinue
            if ($pyl -and $pyl.Source) { $out += $pyl.Source }
            @($out | Select-Object -Unique)
        }
        function Test-ProfileServer {
            try {
                $r = Invoke-WebRequest -Uri "http://127.0.0.1:$ProfilePort/__ds5" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
                return ($r.Content -like "*ds5-profile-server*")
            } catch { return $false }
        }
        function Ensure-ProfileServer {
            if (Test-ProfileServer) { return $true }
            if (-not (Test-Path -LiteralPath $ServerScript)) { return $false }
            foreach ($exe in @(Get-PythonCandidates)) {
                try {
                    $argList = @()
                    if ((Split-Path -Leaf $exe) -ieq "py.exe") { $argList += "-3" }
                    $argList += "`"$ServerScript`""
                    Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -ErrorAction Stop | Out-Null
                } catch { continue }
                for ($i = 0; $i -lt 10; $i++) {
                    Start-Sleep -Milliseconds 300
                    if (Test-ProfileServer) { Log "profile server started via $exe"; return $true }
                }
            }
            return $false
        }
        function Resolve-Browser {
            if (-not $BrowserExe) { return $null }
            if (Test-Path -LiteralPath $BrowserExe) { return $BrowserExe }
            $c = Get-Command $BrowserExe -ErrorAction SilentlyContinue
            if ($c -and $c.Source) { return $c.Source }
            foreach ($g in @("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
                             "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")) {
                if ($g -and (Test-Path -LiteralPath $g)) { return $g }
            }
            return $BrowserExe
        }
        try {
            $target = $restorePath
            if ($restoreQuery) { $target = ([System.Uri]$restorePath).AbsoluteUri + $restoreQuery }
            if ($UseLocalServer -and (Ensure-ProfileServer)) { $target = "http://127.0.0.1:$ProfilePort/" + [System.IO.Path]::GetFileName($restorePath) + $restoreQuery }
            $b = Resolve-Browser
            if ($b) { Start-Process -FilePath $b -ArgumentList "--new-window", "`"$target`"" -ErrorAction Stop | Out-Null }
            else {
                $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = $target; $psi.UseShellExecute = $true
                [System.Diagnostics.Process]::Start($psi) | Out-Null
            }
            Log "native exited -> mix profile restored ($target)"
            if ($b -and $MinimizeBrowser) { Minimize-ProfileWindow }
        }
        catch { Log "FAIL applying mix profile: $($_.Exception.Message)" }
    } else { Log "WARN mix profile not found: $AudioProfile" }
} else { Log "non-native exited -> capture stopped" }
'@
Write-Generated "ds5-global-stop.ps1" $stopPs1

# ===========================================================================
# 3. ds5-start.bat and ds5-stop.bat
# ===========================================================================
$startBat = @'
@echo off
REM ds5-start.bat (generated) - Playnite "before starting a game" launcher.
REM In Playnite Settings -> Scripts, call it as:  "<folder>\ds5-start.bat" "{Name}"
REM chcp 65001 = UTF-8 so accented game names (e.g. the o-umlaut in Ragnarok) survive.
chcp 65001 >nul
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ds5-global-start.ps1" -GameName "%~1"
'@
Write-Generated "ds5-start.bat" $startBat

$stopBat = @'
@echo off
REM ds5-stop.bat (generated) - Playnite "after exiting a game" launcher.
REM In Playnite Settings -> Scripts, call it as:  "<folder>\ds5-stop.bat" "{Name}"
chcp 65001 >nul
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ds5-global-stop.ps1" -GameName "%~1"
'@
Write-Generated "ds5-stop.bat" $stopBat


# ===========================================================================
# 3b. Local profile server (opt-in, see $UseLocalServer) + policy grant bats
# ===========================================================================
$serverPy = @'
# ds5-profile-server.py (generated) - tiny loopback-only static server for the
# profile pages. Why it exists: WebHID device grants do NOT persist for
# file:// pages across browser restarts, so automated profile applies sat
# waiting for a manual "Connect" (unless a connected portal tab happened to be
# open). Grants for the http://127.0.0.1:8377 origin persist like a normal
# website; better yet, ds5-policy.bat pre-grants with no clicks at all. Covers
# forever. Binds 127.0.0.1 only - nothing is exposed to the network.
# Safe under pythonw: request logging is disabled (pythonw has no console).
import http.server
import socketserver
import os

PORT = 8377
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "profiles"))


class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args):  # no stdout/stderr under pythonw; stay silent
        pass

    def do_GET(self):
        if self.path == "/__ds5":  # health check used by the automation scripts
            body = b"ds5-profile-server"
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        return super().do_GET()


socketserver.TCPServer.allow_reuse_address = True
with socketserver.TCPServer(("127.0.0.1", PORT), Handler) as srv:
    srv.serve_forever()
'@
Write-Generated "ds5-profile-server.py" $serverPy

$slotPage = @'
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>DS5 Bridge Config - Slot</title>
<style>body{font-family:system-ui,sans-serif;background:#0f1115;color:#e5e7eb;max-width:560px;margin:60px auto;padding:0 16px}
#b{padding:14px 16px;border-radius:10px;background:#1f2937;font-size:15px}
button{background:#2563eb;color:#fff;border:0;border-radius:8px;padding:10px 16px;font-size:1rem;cursor:pointer;margin-top:12px}</style>
</head><body><div id="b">Activating profile slot&hellip;</div><div id="a"></div>
<script>
const SONY_VID=0x054C, DS5_PID=0x0CE6, DSE_PID=0x0DF2, SET_REPORT=0x80, GET_REPORT=0x81;
// Slot activation replies come back on report 0x84, not 0x81: the config portal
// (a separate browser process) polls 0x81 every second and would otherwise
// consume this reply before we read it. 0x84 is descriptor-declared as a FULL 63-byte report (0x82 is only 9 bytes!) and native-
// unused, so that poll can never collide with slot activation.
const SLOT_REPORT=0x84;
// Worker-based sleep. The automation minimizes this window ~300ms after it
// opens, and Chromium throttles main-thread timers on hidden pages to >=1/sec
// - plain setTimeout stretched this page's ~2s lifetime to 30-60s (which was
// then misread as "window.close() refused"). Workers are exempt, so timing
// stays real even minimized.
const _w=(()=>{try{return new Worker(URL.createObjectURL(new Blob(['onmessage=e=>setTimeout(()=>postMessage(e.data),e.data.ms)'],{type:'text/javascript'})));}catch(_){return null;}})();
let _q=0;const _m=new Map();if(_w)_w.onmessage=e=>{const f=_m.get(e.data.id);if(f){_m.delete(e.data.id);f();}};
const sleep=ms=>_w?new Promise(r=>{const id=++_q;_m.set(id,r);_w.postMessage({id,ms});}):new Promise(r=>setTimeout(r,ms));
// IMPORTANT - DO NOT add visibilitychange/blur handlers that close the HID
// device: minimize fires them ~300ms in, killing the device MID-ACTIVATION -
// the reply poll then spins on a dead handle, the retry throws, the page
// sticks open on CONNECT NEEDED, and whether the slot actually applied is
// luck. That was the pile-up/"native not loading" bug. The device is released
// only in finish() (confirmed success) and by the browser itself on unload.
function isWakeKeyboardIface(d){const c=(d&&d.collections)||[];return c.length>0&&c.every(x=>x.usagePage===0x01&&x.usage===0x06);}
// From v1.23.0 the gyro mouse is a THIRD HID collection on the same VID/PID, so a
// plain match can open the MOUSE and every slot command then fails. Prefer a
// positive match on the gamepad usage; keep exclusion only as a fallback so this
// is never stricter than the VID/PID match that always worked.
function isGamepadIface(d){const c=(d&&d.collections)||[];return c.some(x=>x.usagePage===0x01&&(x.usage===0x04||x.usage===0x05));}
function isMouseIface(d){const c=(d&&d.collections)||[];return c.length>0&&c.every(x=>x.usagePage===0x01&&x.usage===0x02);}
function pickDs5(l){const m=(l||[]).filter(x=>x&&x.vendorId===SONY_VID&&(x.productId===DS5_PID||x.productId===DSE_PID));
  return m.find(isGamepadIface)||m.find(x=>!isWakeKeyboardIface(x)&&!isMouseIface(x))||m[0]||null;}
let device=null;
async function releaseDevice(){try{if(device&&device.opened)await device.close();}catch(_){}}
async function finish(){
  await releaseDevice();               // free our handle first, window fate aside
  try{window.close();}catch(_){}
  await sleep(600);                    // worker-timed: fires on time even minimized
  try{window.close();}catch(_){}
  await sleep(600);
  // Still alive: neutralize so the page holds nothing and is visibly done
  // (the start/stop scripts also sweep leftover slot windows before each run).
  try{document.title='DS5 slot done - closable';document.body.innerHTML=
    '<div id=\'b\' style=\'background:#14532d;padding:14px 16px;border-radius:10px\'>Slot activated \u2713 - you can close this tab.</div>';
  }catch(_){}
}
async function sendCmd(id,args=[]){const p=new Uint8Array(63);p[0]=0x66;p[1]=id;args.forEach((b,i)=>p[2+i]=b);await device.sendFeatureReport(SET_REPORT,p);}
async function reply(id,idx,tries=30){for(let t=0;t<tries;t++){await sleep(60);let r=null;
  try{const d=await device.receiveFeatureReport(SLOT_REPORT);r=new Uint8Array(d.buffer,d.byteOffset,d.byteLength);}catch(_){continue;} // slot reply on 0x84; mid-flash USB stall
  for(let k=0;k<Math.min(4,r.length);k++){if(r[k]===0x66&&r[k+1]===id){const x=r.slice(k);
    if(x[2]===0xFE)break;                 // pending marker: keep polling
    if(idx!==undefined&&x[3]!==idx)break; // stale reply for another slot
    return x;}}}return null;}
function fail(msg){document.title='CONNECT NEEDED - DS5 Bridge Config';const b=document.getElementById('b');b.style.background='#7c2d12';b.textContent=msg;
  document.getElementById('a').innerHTML='<button onclick="run(true)">Connect &amp; Activate</button>';}
async function run(gesture){
  const slot=parseInt(new URLSearchParams(location.search).get('slot')||'0',10);
  const b=document.getElementById('b');
 if(!(slot>=1&&slot<=32)){b.textContent='Bad or missing ?slot=1..32';return;}
  try{
    device=pickDs5(await navigator.hid.getDevices());
    if(!device&&gesture){const p=await navigator.hid.requestDevice({filters:[{vendorId:SONY_VID,productId:DS5_PID},{vendorId:SONY_VID,productId:DSE_PID}]});device=pickDs5(p)||(p&&p[0]);}
    if(!device){fail('No granted device - click to connect and activate slot '+slot+'.');return;}
    if(!device.opened)await device.open();
    let r=null;
    for(let a=0;a<2&&!(r&&(r[2]===0x00||r[2]===0x02));a++){ // one silent retry (flash settle)
      if(a)await sleep(800);
      await sendCmd(0x09,[slot-1]);
      r=await reply(0x09,slot-1);
    }
    // status 0x00 = activated+persisted; 0x02 = ACTIVATED but flash persist
    // deferred (core busy at launch) - settings are live, treat as success.
    if(!r||(r[2]!==0x00&&r[2]!==0x02)){
      const st=r?('status 0x'+r[2].toString(16)+', stage '+r[5]):'no reply (timeout)';
      fail('Slot '+slot+' activation failed ('+st+'). Stages: 1=bad slot, 2=slot unreadable/empty, 3=persist.');return;}
    if(r[4]===1){b.textContent='Slot '+slot+' active - device re-enumerating...';try{await sendCmd(0x03);}catch(_){}}
    b.style.background='#14532d';b.textContent='Profile slot '+slot+' activated \u2713';
    document.title='DS5 Bridge Config';
    await finish();
  }catch(e){fail('Error: '+e.message);}
}
run(false);
</script></body></html>
'@
Write-Generated "profiles\slot-activate.html" $slotPage

$policyBat = @'
@echo off
REM ds5-policy.bat (generated) - RECOMMENDED one-time setup. Writes the
REM Chromium policy "WebHidAllowDevicesForUrls" so the dongle (VID 054C,
REM PID 0CE6/0DF2) is PRE-GRANTED to the profile pages: no Connect click is
REM ever needed and nothing is lost when the browser closes or clears site
REM data. Side effect: Edge/Chrome show "Managed by your organization".
REM Fully reversible: run ds5-policy-remove.bat.
REM Requires admin (self-elevates). Restart the browser after running.

net session >nul 2>&1
if errorlevel 1 (
  echo Requesting administrator rights...
  powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
  exit /b
)

set "POLICY=[{\"devices\":[{\"vendor_id\":1356,\"product_id\":3302},{\"vendor_id\":1356,\"product_id\":3570}],\"urls\":[\"file:///\",\"http://127.0.0.1:8377\"]}]"

reg add "HKLM\SOFTWARE\Policies\Microsoft\Edge"  /v WebHidAllowDevicesForUrls /t REG_SZ /d "%POLICY%" /f >nul
reg add "HKLM\SOFTWARE\Policies\Google\Chrome"   /v WebHidAllowDevicesForUrls /t REG_SZ /d "%POLICY%" /f >nul
echo.
echo Policy installed for Edge and Chrome.
echo Close ALL browser windows and reopen - profile pages then connect
echo silently, permanently. Verify at edge://policy if curious.
echo Undo anytime with ds5-policy-remove.bat.
pause
'@
Write-Generated "ds5-policy.bat" $policyBat

$policyRemoveBat = @'
@echo off
REM ds5-policy-remove.bat (generated) - undoes ds5-policy.bat completely:
REM deletes the WebHidAllowDevicesForUrls policy from Edge and Chrome.
REM Requires admin (self-elevates). Restart the browser afterwards; the
REM "Managed by your organization" notice disappears (unless other policies
REM exist on this machine).
net session >nul 2>&1
if errorlevel 1 (
  echo Requesting administrator rights...
  powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
  exit /b
)
reg delete "HKLM\SOFTWARE\Policies\Microsoft\Edge" /v WebHidAllowDevicesForUrls /f >nul 2>&1
reg delete "HKLM\SOFTWARE\Policies\Google\Chrome"  /v WebHidAllowDevicesForUrls /f >nul 2>&1
echo Policy removed. Restart the browser.
pause
'@
Write-Generated "ds5-policy-remove.bat" $policyRemoveBat


# ===========================================================================
# 4. native-games.txt  (only if it doesn't already exist)
# ===========================================================================
$nativeList = Join-Path $Base "native-games.txt"
if (-not (Test-Path -LiteralPath $nativeList)) {
    $tpl = @'
# DS5 native-haptics games - one game name (or a distinctive part of it) per line.
# Matching is case-insensitive and partial: "Ratchet" matches "Ratchet & Clank: Rift Apart".
# Games listed here use native DualSense haptics (auto-haptics OFF, no ds5audio).
# Everything NOT listed uses the mix profile + ds5audio capture.
# Lines starting with # are ignored. Use a unique word to avoid false matches.
# Accented titles work as-is (matching is encoding-tolerant), so "Ragnarök"
# matches even if the name arrives with mangled characters.
#
# Default list of PC games with native DualSense haptics - adjust to your library:
Returnal
God of War Ragnarök
PRAGMATA
Indiana Jones and the Great Circle
Ratchet & Clank: Rift Apart
Until Dawn
Alan Wake II: Deluxe Edition
Days Gone
DOOM: The Dark Ages
The Last of Us Part I
Marvel's Spider-Man 2
Prince of Persia The Lost Crown
SILENT HILL 2
'@
    Set-Content -LiteralPath $nativeList -Value $tpl -Encoding UTF8
    Write-Host "  wrote native-games.txt (template - edit it with your games)"
} else {
    Write-Host "  kept existing native-games.txt (not overwritten)"
}

# ===========================================================================
# 5. profile-overrides.txt  (only if it doesn't already exist)
# ===========================================================================
$ovrList = Join-Path $Base "profile-overrides.txt"
if (-not (Test-Path -LiteralPath $ovrList)) {
    $tpl2 = @'
# DS5 per-game profile overrides - apply a CUSTOM profile for specific games
# instead of the default audio-mix / native-off pair. One rule per line:
#
#   name fragment = slot N                      (dongle profile slot, fw 1.1.2+)
#   name fragment = profile-file.html            (exported profile file)
#   ... either form takes an optional ", audio" or ", noaudio" flag,
#       and any further comma-separated text is passed to ds5audio, e.g.
#   name fragment = slot N, audio, --map front
#
# - The fragment matches the Playnite game name (case-insensitive, partial,
#   accent/encoding tolerant - same rules as native-games.txt).
# - "slot N" (or "slot:N", N = 1-24) activates a profile saved on the dongle in
#   the portal's Profile Slots panel - a single instant command; preferred.
# - The file form points at an exported .autoapply.html placed in profiles\.
# - Optional flag: ", audio" also runs the ds5audio capture, ", noaudio" skips
#   it. Without a flag, native-games.txt decides the capture as usual. A game
#   on the native list therefore needs an explicit ", audio" if its custom
#   profile is meant to run the capture as well.
# - Anything else after a comma is handed to ds5audio.py, so a profile can
#   carry the channel mapping it needs (", --map front" for a game whose own
#   haptics must stay on ch3/4, ", --map rear" to isolate native speaker
#   audio). These are added to the global $AudioArgs in the start script.
# - First matching line wins. Lines starting with # are ignored.
# - On game exit the mix profile is restored automatically (unless the custom
#   profile IS the mix profile).
#
# Examples - replace with your own:
#Cyberpunk = slot 3
#Elden Ring = slot 4, noaudio
#Resident Evil 4 = slot 5, audio, --map front
#Doom = doom-recoil.autoapply.html, audio
#Stray = stray-soft-triggers.autoapply.html
'@
    Set-Content -LiteralPath $ovrList -Value $tpl2 -Encoding UTF8
    Write-Host "  wrote profile-overrides.txt (template - optional)"
} else {
    Write-Host "  kept existing profile-overrides.txt (not overwritten)"
}

# ===========================================================================
Write-Host ""
Write-Host "Done. In Playnite -> Settings -> Scripts, paste these into the SCRIPT boxes:"
Write-Host ""
Write-Host "  Executing before starting a game:"
Write-Host "    & `"$Base\ds5-start.bat`" `"{Name}`""
Write-Host ""
Write-Host "  Executing after exiting a game:"
Write-Host "    & `"$Base\ds5-stop.bat`" `"{Name}`""
Write-Host ""
Write-Host "One-time: run ds5-policy.bat (admin, self-elevates) so profile pages are"
Write-Host "pre-granted access to the dongle - no Connect clicks, survives restarts."
Write-Host "Reversible with ds5-policy-remove.bat."
Write-Host ""
Write-Host "Notes:"
Write-Host " - Use the .bat calls above with {Name}. If the log shows game: '' on start,"
Write-Host "   the start script falls back to reading Playnite's own log for the name."
Write-Host " - native-games.txt matching is partial, case-insensitive and encoding-"
Write-Host "   tolerant; accented titles like 'God of War Ragnarök' work as written."
Write-Host " - Activity is logged to ds5-automation.log in this folder."
Write-Host ""
Read-Host "Press Enter to close"
